tap 'Goles/battery'
tap 'gapple/services'
tap 'thoughtbot/formulae'

cask 'spectacle'

brew 'battery'
brew 'coreutils'
brew 'elixir'
brew 'forego'
brew 'fzf'
brew 'ghc'
brew 'gpg2'
brew 'gpgme'
brew 'memcached'
brew 'mysql'
brew 'parity'
brew 'qt5'
brew 'reattach-to-user-namespace'
brew 'tmate'
brew 'vim'
brew 'watchman'
brew 'wget'
brew 'zsh-syntax-highlighting'
