tap 'gapple/services'
tap 'thoughtbot/formulae'

cask 'dropbox'
cask 'flux'
cask 'firefox'
cask 'google-chrome'
cask 'gpgtools'
cask 'java'
cask 'licecap'
cask 'onepassword'
cask 'postgres'
cask 'screenhero'
cask 'silverlight'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'

brew 'coreutils'
brew 'gpg2'
brew 'gpgme'
brew 'forego'
brew 'iojs'
brew 'mysql'
brew 'ngrok'
brew 'parity'
brew 'phantomjs'
brew 'reattach-to-user-namespace'
brew 'solr'
brew 'tree'
brew 'watchman'
brew 'zsh-syntax-highlighting'

brew 'nviennot/tmate/tmate'
