#!/bin/sh

alias g='git'
alias ga='git aa'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp='git push'
alias gpf='git push -f'
alias gd='git diff'
alias gc='git commit -v'
alias gca='git commit -a -v'
alias gco='git checkout'
alias gb='git branch'
alias gs='git status -sb'
alias grc='git rebase --continue'
alias gri='git -c commit.verbose=true rebase --interactive origin/master'
alias gwip='git add -A && git commit -am "WIP"'
