#!/bin/sh

alias g='git'
alias ga='git aa'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp='git push'
alias gpf='git push -f'
alias gd='git diff'
alias gc='git commit -v'
alias gca='git commit -a -v'
alias gco='git checkout'
alias gb='git branch'
alias gs='git status -sb'
alias grc='git rebase --continue'
alias gri='git up --interactive --keep-empty'
alias groot='git rebase --interactive --root --keep-empty'
alias gwip='git add -A && git commit -am "WIP"'
alias gpr="git log HEAD...main --reverse --format='%s%n===%n%n%b'"
